apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: country-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: country-service
  namespaceSelector:
    matchNames:
      - jenkins  # le namespace où est déployé ton service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
